/* eslint-disable no-undef */
module.exports = {
  apps: [
    {
      name: 'watchr-api',
      script: 'dist/server.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 4500,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 4500,
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-import-worker',
      script: 'dist/workers/startImportWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/import-worker-error.log',
      out_file: './logs/import-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-episode-sync-worker',
      script: 'dist/workers/startEpisodeSyncWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/episode-sync-worker-error.log',
      out_file: './logs/episode-sync-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-notification-worker',
      script: 'dist/workers/startNotificationWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/notification-worker-error.log',
      out_file: './logs/notification-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-trakt-sync-worker',
      script: 'dist/workers/startTraktSyncWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/trakt-sync-worker-error.log',
      out_file: './logs/trakt-sync-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-username-fix-worker',
      script: 'dist/workers/startUsernameFixWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/username-fix-worker-error.log',
      out_file: './logs/username-fix-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-news-sync-worker',
      script: 'dist/workers/startNewsSyncWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/news-sync-worker-error.log',
      out_file: './logs/news-sync-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-reengagement-worker',
      script: 'dist/workers/startReengagementWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/reengagement-worker-error.log',
      out_file: './logs/reengagement-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-activation-nudge-worker',
      script: 'dist/workers/startActivationNudgeWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/activation-nudge-worker-error.log',
      out_file: './logs/activation-nudge-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-ban-scheduler-worker',
      script: 'dist/workers/startBanSchedulerWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/ban-scheduler-worker-error.log',
      out_file: './logs/ban-scheduler-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-scheduled-send-worker',
      script: 'dist/workers/startScheduledSendWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/scheduled-send-worker-error.log',
      out_file: './logs/scheduled-send-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-email-worker',
      script: 'dist/workers/startEmailWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/email-worker-error.log',
      out_file: './logs/email-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-moderation-worker',
      script: 'dist/workers/startModerationWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/moderation-worker-error.log',
      out_file: './logs/moderation-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
    {
      name: 'watchr-status-monitor-worker',
      script: 'dist/workers/startStatusMonitorWorker.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
      },
      env_development: {
        NODE_ENV: 'development',
      },
      error_file: './logs/status-monitor-worker-error.log',
      out_file: './logs/status-monitor-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '500M',
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4500,
    },
  ],
};
